### ISSUE TITLE
Please make this repo public

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-test#1]
As soon as possible, please make this repo public. Please leave this Issue open until we make it public.

 

Tracking Page:

[Open Sourcing Cortx-Test and CORIO - Private-Cortx - Confluence (atlassian.net)|https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/898039873/Open+Sourcing+Cortx-Test+and+CORIO]

**Comment by johnbent** [comment]
Talked to @seagate-sarang-sawant and went ahead and made it public.

**Comment by cortx-admin** [comment]
> SARANG SAWANT commented in Jira Server:

[~535110] ,  I would request you to wait till we have an internal QA team meeting till tomorrow.  We are almost completed opensource Cortx-Test  tasks and there is some tail ending work of  updating Read me as per user reviews conducted within team.  Most probably will be done by tomorrow with needed changes.

cc [~933890] / [~521878] /[~522044]

**Comment by cortx-admin** [comment]
> SARANG SAWANT commented in Jira Server:

cortx-test is now opensource repository. We Cortx QA team has fixed essential Codacy issues and long pending tech debt items.  The remaining Codacy fixes and test libraries and commons cleanup/refactoring  will be taken in I & P.

**Comment by cortx-admin** [comment]
> SARANG SAWANT commented in Jira Server:

Cortx-Test is public now. 

1) CLA, Codacy, DCO, Whitesource are enabled.

2) All plain passwords are removed

3) Critical Codacy fixes across the repository and some part  of tech debt is addressed. 

Some pending work will be taken in I & P sprint.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~755344] [~535110]

Who takes up closure of this?
