### ISSUE TITLE
Reduce the number of pytest marker for deployment tests

### ISSUE THREAD

**Issue by seagate-sarang-sawant** [Seagate/cortx-test#1514]
### Problem

Test Environment field from Jira TE is used to mention the deployment tags used to group the test cases.  We don't want these tags to propagate in code as tests are writing for N+ (N = 3 nodes) cluster deployment. 

What we want is to have cluster_deployment as the test env tag.  If the nodes in a cluster is 3 or 4 or N , it can be put in Jira labels. The setup entry or the Common config is aware of the number of nodes (CMN_CFG["nodes"]) in the cluster and test should be using that value in the test or lib code. 

Currently used tags are mention in the list below. 
    three_node_deployment
    four_node_deployment
    five_node_deployment
    six_node_deployment
    seven_node_deployment
    eight_node_deployment
    nine_node_deployment
    ten_node_deployment
    eleven_node_deployment
    twelve_node_deployment
    thirteen_node_deployment
    fourteen_node_deployment
    fifteen_node_deployment
    
A better solution needs to be identified and developed to reduce the number of invalid tags in code base. 

### Expected behavior

A better solution needs to be identified and developed to reduce the number of invalid tags in code base. "cluster_deployment" tag should be used as the test env tag. 

### How to reproduce

Refer pytest.ini file for three_node_deployment, four_node_deployment, etc tags. This is a design issue.

### Deployment information

NA

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31243. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
