### ISSUE TITLE
Refine Telnet_helper for exception handling.

### ISSUE THREAD

**Issue by kachhwahadivya** [Seagate/cortx-test#22]
Why are we using generic exception to handle error/exceptions .  Figure out what exception you want to handle e.g. socket exception and then do handling .  
Also, are you connecting telnet in this function and why it is named as connect ?     Alternatively you may pull connection code and make it as a behavior.

_Originally posted by @seagate-sarang-sawant in https://github.com/Seagate/cortx-test/pull/16#discussion_r556459230_

**Comment by hessio** [comment]
Hi @kachhwahadivya can we close this issue?
