### ISSUE TITLE
Rework write_yaml function so that it will load file in process memory

### ISSUE THREAD

**Issue by kachhwahadivya** [Seagate/cortx-test#23]
This file won't be reloaded in the process memory. Do you plan to add the load function?

_Originally posted by @seagate-sarang-sawant in https://github.com/Seagate/cortx-test/pull/16#r554897405_

**Comment by hessio** [comment]
Hi @kachhwahadivya  can we close this issue?

**Comment by kachhwahadivya** [comment]
@seagate-sarang-sawant : Can u suggest?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
